# Generated by Django 6.0.2 on 2026-03-06 16:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Order Number')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('confirmed', 'Confirmed'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='Order Date')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='Expected Date')),
                ('subtotal', models.DecimalField(decimal_places=2, default='0', max_digits=12, verbose_name='Subtotal')),
                ('tax_amount', models.DecimalField(decimal_places=2, default='0', max_digits=12, verbose_name='Tax Amount')),
                ('total', models.DecimalField(decimal_places=2, default='0', max_digits=12, verbose_name='Total')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'db_table': 'purchase_orders_purchaseorder',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='Tax Id')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'db_table': 'purchase_orders_supplier',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('quantity', models.DecimalField(decimal_places=2, default='1', max_digits=10, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, default='0', max_digits=12, verbose_name='Unit Price')),
                ('total', models.DecimalField(decimal_places=2, default='0', max_digits=12, verbose_name='Total')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchase_orders.purchaseorder')),
            ],
            options={
                'db_table': 'purchase_orders_purchaseorderline',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='purchase_orders.supplier'),
        ),
    ]
